### ISSUE TITLE
 could I take the  Quran images to make another app?

### ISSUE THREAD

**Issue by boussadjra** [atefBB/quran-react-app#1]
Salam akhi, baraka allaho fika for this work, could I take the  Quran images to make another app?

**Comment by atefBB** [comment]
@boussadja
<div dir="rtl">وعليكم السلام ورحمة الله وبركاته، وفيك بارك الله. نعم خذ واذكرنا بخير.</div>
<div dir="rtl">ملاحظة: المصحف المأخوذ منه الصور هو برواية ورش من طريق اﻷصبهاني.</div>

**Comment by atefBB** [comment]
<div dir="rtl">ملاحظة: المصحف المأخوذ منه الصور هو برواية ورش من طريق اﻷصبهاني.</div>

**Comment by boussadjra** [comment]
جزاك الله خيرا و جعل العمل في ميزان حسناتك

**Comment by atefBB** [comment]
<div dir="rtl">آمين آمين</div>
